export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const ARTICLE_FILTER_SELECTED = 'ARTICLE_FILTER_SELECTED'

export const ARTICLE_FILTER_RANGE_CHANGED = 'ARTICLE_FILTER_RANGE_CHANGED'
